from app.repositories.price_history_repository import create_price_history


def main():
    # Save the first observed price for product ID 1
    history = create_price_history(
        product_id=1,
        price=79.99,
        available=True,
    )

    # Display the ID generated by PostgreSQL
    print(f"Price history created with ID: {history.id}")


# Run the main function when this file is executed directly
if __name__ == "__main__":
    main()